#ifndef GFX_SCREEN_CONFIG_H
#define GFX_SCREEN_CONFIG_H

/*
#define DESIRED_SCREEN_WIDTH 1152
#define DESIRED_SCREEN_HEIGHT 864

#define USE_LOW_LATENCY 
*/

#define DESIRED_SCREEN_WIDTH 800
#define DESIRED_SCREEN_HEIGHT 600

#endif
