#ifndef GFX_SCREEN_CONFIG_H
#define GFX_SCREEN_CONFIG_H

/*
#define DESIRED_SCREEN_WIDTH 1152
#define DESIRED_SCREEN_HEIGHT 864

#define DESIRED_SCREEN_WIDTH 800
#define DESIRED_SCREEN_HEIGHT 600

#define DISABLE_SYNC

#define SAMPLING_COUNT 1
#define SAMPLING_QUALITY 0
*/

#endif
